### ISSUE TITLE
About set GPU  ID

### ISSUE THREAD

**Issue by liuchanfeng165** [Freedomxt/new_reid#1]
os.environ['CUDA_VISIBLE_DEVICES'] = '1'

hi , the repo owner, In  u repo , it sets '1'  of GPU to train but only  '0'  of GPU not '1' . Do u meet this problem?

**Comment by Freedomxt** [comment]
Hi，you can delete this line.

**Comment by liuchanfeng165** [comment]
> Hi，you can delete this line.

hmmm,actually , I  need GPU1 to run but  GPU0 。finnally, I solve it by modified evaluator.
